### ISSUE TITLE
TODO for `package:messages`

### ISSUE THREAD

**Issue by mosuem** [dart-lang/i18n#816]
- [ ] Reduce overlap between `.g.dart` files, such as sharing `pluralSelector`.
- [ ] Replace `build_runner` by `build.dart` for generating data files.
- [ ] Replace `build_runner` by macros for generating code.
